#!/usr/bin/env python
import os
from os.path import dirname, join, realpath

EXC_DIR = join(dirname(realpath(__file__)), 'src')
os.chdir(EXC_DIR)
os.system('node_modules/.bin/riot . static/js/tags.js')
